<?php

########################################################################
# Extension Manager/Repository config file for ext: "magento_sync"
#
# Auto generated by Extension Builder 2012-10-15
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Magento Connector',
	'description' => 'Synchronizing
- Users
- Content',
	'category' => 'misc',
	'author' => 'Tim Ruether',
	'author_email' => 'tim@holosystems.de',
	'author_company' => 'holosystems',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>