<?php
/**
 * Holosystems_Typo3connector extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category	Holosystems
 * @package		Holosystems_Typo3connector
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * template
 *
 * @category	Holosystems
 * @package		Holosystems_Typo3connector
 * @subpackage	Template
 *
 * @see app/code/community/Holosystems/Typo3connector/Block/Typo3connector.php
 * @var $this Holosystems_Typo3connector_Block_Typo3connector
 */
?>
<?php if (isset($content)): ?>
	<?php echo $content ?>
<?php endif ?>